### ISSUE TITLE
Various Errors

### ISSUE THREAD

**Issue by DrDoomDEU** [TitansBane/Elysium#231]
![image](https://user-images.githubusercontent.com/69747498/142935350-bb887399-7814-4966-a602-1c19a09d99bb.png)

![image](https://user-images.githubusercontent.com/69747498/142935391-a2d49f7e-16fd-4e4a-b178-e4aec1741090.png)

**Comment by DrDoomDEU** [comment]
![image](https://user-images.githubusercontent.com/69747498/142935490-a015fd3b-d48f-410b-8eae-9814cc92453f.png)

**Comment by Kadebass** [comment]
hast du den Unofficial Skyrim Special Edition Downgrade Patcher (https://www.nexusmods.com/skyrimspecialedition/mods/57618) benutzt? Sieht nicht danach aus. Dieses Modpack setzt bislang Skyrim SE 1.5.97 voraus, die AE ist höher, ist 1.6.XX. Geht (noch ??) nicht mit der Änniversäry Ädischn...

**Comment by cburkett2021** [comment]
I have encountered the same issue, I ran the downgrade patcher to 1.5.97.0 and am still having the same error. Anyone able to get this working yet?

**Comment by Kadebass** [comment]
Skyrim must be installed in english for the downgrade patcher and for Elysium as well.  I've changed the language settings only (in steam options and Skyrim.ini) after a german installation of Skyrim, what causes in silent npc's in my nonmodded Skyrim AE (hopefully) in english. I've tested it after. I thought Steam should refresh the data for the language, but it doesn't. So, i prefer a fresh, clean installation/redownload of english Skyrim AE! That does it for me, maybe and why not for you too? Just be sure that Skyrim AE runs well in english before downgrading and installing Elysium. i'm not sure but i mean, in the log file of Wabbajack, wabbajack is crying because of wrong/non expected/non existing Skyrim data. If anything else was going wrong, i can't see it. The downgrade patcher comes with a log window too, and what it displays, is wrong to post it  here for sure, but you could see some usefull information. It can not and will not touch wrong files and displays it.
