### ISSUE TITLE
Nemesis.Unlimited.Behavior.Engine missing download

### ISSUE THREAD

**Issue by welyndowd** [TitansBane/Elysium#249]
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7715192/Wabbajack.current.log)

Have ran the downgrader patch which got me past my initial issues, I then downloaded the xLODGen.84.7z file 

Now getting the missing Nemesis Unlimited behaviour error.  Any help?

**Comment by thortilla** [comment]
Hello,

You can download it from nexus at the moment:
https://www.nexusmods.com/skyrimspecialedition/mods/60033?tab=description

Mod creator says that from now on it will be uploaded to nexus instead of mega. I'm sure Elysium creator will fix it soon, until then let's do the same as you did with xLODGen.

**Comment by welyndowd** [comment]
That worked perfectly, thank you.  All now installed and ready for me to revisit.
