### ISSUE TITLE
Low FPS without any good reason

### ISSUE THREAD

**Issue by Spacehonky** [TitansBane/Elysium#253]
I am running Elysium on an NZXT prebuilt that features an RTX 3090 and 32GB of VRAM. I know full well that I could render the entirety of Tamriel all the way down to atoms, yet this game has confounded even the sheer power I have presented it with.

The beginning of my playthrough was stellar, with the beautiful overhauls really shining as I trekked to Whiterun for the very first time. It was in this particular hold that my FPS had a heart attack. I understand rendering a ton of NPCs, fire effects, wind, smoke etc is difficult for a PC of any kind, but given the specs I listed above this doesn't really make sense; surely Whiterun isn't inhabiting 25GB of VRAM? I checked the advanced Windows Task Manager to get an actual grasp on the power draw and saw that SSE was pulling about 5GB while standing inside Whiterun's gate facing the most populated angle in the city. Why, then, am I having FPS chokes?

I don't know enough about internal hardware to troubleshoot this issue without help, so I would greatly appreciate some advice!

**Comment by haikohh** [comment]
I also suffer severe FPS/stuttering issues, most prominently in whiterun. RTX 3080, Ryzen 7 3700x, 32gb RAM. I believe this comes down to the fact that Skyrim is built on an engine that caps itself at 60 fps by design (otherwise the physics break), and then adding hundreds of graphical mods + ENB. I'm not sure, but using mods that allow to unlock the framerate may help people like us with higher end systems see better performance, as the game itself would no longer be running max 60 fps, allowing more headroom for mods and ENB. I don't have much modding experience, so I wouldn't know how to get these working with Elysium. If anybody knows a workaround/fix for these FPS issues on high-end systems, I would love to hear it.

**Comment by Spacehonky** [comment]
Ditto what he said. Would an uncap fps mod fix it, and if so where do I find it?

**Comment by haikohh** [comment]
Found a method of uncapping fps that may be of use. Havok fix is a mod designed to allow for uncapped fps without breaking the engine. Here is a thread about it: https://www.reddit.com/r/skyrimmods/comments/ekas2n/friendly_reminder_fps_over_60_is_already_doable/

Here is the link to download: https://www.nexusmods.com/skyrimspecialedition/mods/18160

It's also entirely possible that the sheer amount of mods included in Elysium will bring any system to its knees, as mods will never be as optimized as built-in features. If you have a chance to test this fix before I do, please let me know.

**Comment by Spacehonky** [comment]
A simple install showed no discernable difference in performance. I think you're right about having to modify load order and dependencies, but I am simply not experienced enough with MO2 to figure it out.
