### ISSUE TITLE
New game load takes forever

### ISSUE THREAD

**Issue by XelaDK** [TitansBane/Elysium#47]
Hi, i have downlaoded elysium, and it can start up and everything, but when i press new game all text dissapear and the main screen is the only thing i see, it have been sitting like this for 30 minutes now, my Memory and CPU is running at 40% in the task manager so it shouldnt be that

-XelaDK

**Comment by seventhbrigade** [comment]
I had this problem too, to fix it you have to uninstall Skyrim, delete the game directory in your steam folder, then delete the Skyrim folder under Documents > My Games, reinstall Skyrim and update the mod pack on Wabbajack.

**Comment by XelaDK** [comment]
Yo, Thank you this worked!

**Comment by mickyds33** [comment]
I had this issue a few days ago when I first installed the modpack, and here is how I personally fixed this.
Firstly I followed the instructions listed by Seventh Brigade and this did not work for me personally. but if it does of you guys then great!
What I did that fixed this problem was I went back to the main page for the modpack and looked at the Post-Installation section particularly this one. 
![image](https://user-images.githubusercontent.com/27994490/110232904-e29ff600-7f74-11eb-8878-5267283d2563.png)
 and doing that simple step just fixed this problem for me for some reason.
