### ISSUE TITLE
Occasional crashes while loading a saved game after dying

### ISSUE THREAD

**Issue by LukaMrkonjic** [TitansBane/Elysium#77]
I've been having occasional CTD's while loading my save games, usually after dying. I'm not sure if I can distill a common factor, but I'm sure there is one.

Here's some crash logs:
[Crash_2021_4_11_17-15-41.txt](https://github.com/TitansBane/Elysium/files/6302228/Crash_2021_4_11_17-15-41.txt)
[Crash_2021_4_11_20-21-23.txt](https://github.com/TitansBane/Elysium/files/6302230/Crash_2021_4_11_20-21-23.txt)
[Crash_2021_4_12_12-41-52.txt](https://github.com/TitansBane/Elysium/files/6302231/Crash_2021_4_12_12-41-52.txt)
[Crash_2021_4_11_15-55-44.txt](https://github.com/TitansBane/Elysium/files/6302232/Crash_2021_4_11_15-55-44.txt)

Cheers, and keep up the good work!

**Comment by joe-woodhouse** [comment]
Are the save games Autosaves? Have you applied any Elysium updates?

Asking because those were what caused my CTDs. Apologies if you know all this already - I didn't until I was trying to deal with my own CTDs, which may or may not be the same as yours.

The Autosave CTDs are reduced but not fully eliminated by loading full/normal saves rather than Autosaves, because typically there are many more scripts running after a transition that causes an Autosave, and those scripts may not have completed running at the instant of the Autosave. A full save usually occurs at a "quieter" script moment and usually there are none in progress. It's a good habit to get into to do a full normal save a minute after any Autosave.

Re. Elysium updates, I normally am an enthusiastic patcher of anything and everything, and I assumed that an update to Elysium meant an improvement in game experience that of course I'd want to have. More fool me, I should've read the changelog which discloses that many (most?) Elysium updates break games in progress and are intended only for brand new games.

While I myself don't quite understand the design intentions in releasing a patch that breaks all games in progress (who is the patch for, then?), I acknowledge that the documentation is quite clear on this point and I'm a fool for updating and then wondering why I was getting CTDs in my game.

If by chance you or someone else has done the same thing as me, you _may_ be able to do some surgery on your save game to prevent your CTDs. Look into "ReSaver" which is a tool that scans savegame files and can attempt to remove references to mods that don't exist any more. It doesn't always work, and by golly you have to read and follow the instructions _exactly_, but it fixed my CTDs and allowed me to continue my game with 150+ hours in it.

Since you can copy a savegame file, preserve the copy, attempt surgery on the original, and fallback to the copy if surgery doesn't work, you have nothing to lose in seeing if ReSaver fixes your CTDs regardless of their cause. Good luck.
